name: 'bomber'
description: 'Generates a Software Bill Of Materials (SBOM) from container images and filesystems'
author: mikey strauss
inputs:
  # command:
  #   description: 'command <bomb-syft>'
  #   default: bomb-syft
  type:
    description: 'target type'
    default: oci-registry
  target:
    description: 'target'
    required: true
  verbose:
    description: 'increase verbosity (-v = info, -vv = debug)'
    default: 0
  config:
    description: 'application config file'
  output:
    description: 'report output formatter, options=[cyclonedxjson cyclonedxxml] (default "cyclonedxjson")'
    default: cyclonedxjson
  output-directory:
    description: 'report output directory'
    default: ./bomber_reports
  attest:
    description: 'attest image bom'
    default: false
  attestconfig:
    description: 'cocosign configuration path'
  attestname:
    description: 'cocosign configuration name'

runs:
  using: docker
  image: docker://scribesecuriy.jfrog.io/scribe-docker-public-local/bomber:latest 
  args:
    - bomb-syft
    - ${{ inputs.type }}:${{ inputs.target }}
    - --verbose=${{ inputs.verbose }}
    - ${{ inputs.config && '--config=' }}${{ inputs.config }}
    - --output=${{ inputs.output }}
    - --output-directory=${{ inputs.output-directory }}
    - --attest=${{ inputs.attest }}
    - ${{ inputs.attestconfig && '--attest.config=' }}${{ inputs.attestconfig }}
    - ${{ inputs.attestname && '--attest.name=' }}${{ inputs.attestname }}
    - -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_WORKFLOW -e GITHUB_ACTOR -e GITHUB_EVENT_NAME -e GITHUB_JOB -e GITHUB_WORKSPACE -e GITHUB_REPOSITORY_OWNER -e GITHUB_REPOSITORY -e GITHUB_SHA -e GITHUB_REF -e GITHUB_SERVER_URL
branding:
  icon: shield
  color: green
