name: 'bomber'
description: 'Generates a Software Bill Of Materials (SBOM) from container images and filesystems'
author: mikey strauss
inputs:
  command:
    description: 'command'
    default: bomb-syft
  type:
    description: 'target type'
    default: oci-registry
  target:
    description: 'target'
    required: true
  verbose:
    description: 'verbose count <0 Err -> 2 Debug>'
    default: 0
  config:
    description: 'config path'
  name:
    description: 'name of configuration'
    default: bomber

runs:
  using: docker
  image: docker://scribesecuriy.jfrog.io/scribe-docker-public-local/bomber:latest 
  args:
    - ${{ inputs.command }}
    - ${{ inputs.type }}:${{ inputs.target }}
    - --verbose=${{ inputs.verbose }}
    - ${{ inputs.config && '--config='inputs.config }} }}

branding:
  icon: shield
  color: green
