name: 'bomber'
description: 'Generates a Software Bill Of Materials (SBOM) from container images and filesystems'
author: mikey strauss
inputs:
  config:
    description: 'config path'
    default: .cocosign.yaml
  name:
    description: 'name of configuration'
    default: bomber
  command:
    description: 'command'
    default: bomb-syft
  type:
    description: 'target type'
    default: oci-registry
  target:
    description: 'target'
    required: true
  verbose:
    description: 'verbose count <0 Err -> 2 Debug>'
    default: 0


runs:
  using: docker
  image: docker://scribesecuriy.jfrog.io/scribe-docker-public-local/bomber:latest 
  args:
    - ${{ inputs.command }}
    - ${{ inputs.type }}:${{ inputs.target }}
    - --verbose=${{ inputs.verbose }}
branding:
  icon: shield
  color: green
