name: 'bomber'
description: 'Generates a Software Bill Of Materials (SBOM) from container images and filesystems'
author: mikey strauss
inputs:
  command:
    description: 'command'
    default: bomb-syft
  type:
    description: 'target type'
    default: oci-registry
  target:
    description: 'target'
    required: true
  verbose:
    description: 'increase verbosity (-v = info, -vv = debug)'
    default: 0
  config:
    description: 'application config file'
  output:
    description: 'report output formatter, options=[cyclonedxjson cyclonedxxml] (default "cyclonedxjson")'
    default: cyclonedxjson
  output-directory:
    description: 'report output directory'
    default: ./bomber_reports


runs:
  using: docker
  image: docker://scribesecuriy.jfrog.io/scribe-docker-public-local/bomber:latest 
  args:
    - ${{ inputs.command }}
    - ${{ inputs.type }}:${{ inputs.target }}
    - --verbose=${{ inputs.verbose }}
    - ${{ inputs.config && '--config=' }}${{ inputs.config }}
    - --output=${{ inputs.output }}
    - --output-directory=${{ inputs.output-directory }}

branding:
  icon: shield
  color: green
