name: 'Gensbom: bom'
description: 'Generates a Software Bill Of Materials (SBOM) from container images and filesystems'
author: Mikey Strauss
outputs:
  output-file:
    description: 'Bom output file path'
inputs:
  type:
    description: 'Target source type options=[docker,docker-archive, oci-archive, dir, registry]'
    default: registry
  target:
    description: 'Target object name format=[<image:tag>, <dir_path>]'
    required: true
  verbose:
    description: 'Increase verbosity (-v = info, -vv = debug)'
    default: 1
  config:
    description: 'Application config file'
  format:
    description: 'Sbom formatter, options=[cyclonedx-json cyclonedx-xml attest-cyclonedx-json statement-cyclonedx-json]'
  output-directory:
    description: 'Report output directory'
    default: ./scribe/gensbom
  output-file:
    description: 'Output result to file'
  name:
    description: 'Custom/project name'
  label:
    description: 'Custom label'
  env:
    description: 'Custom env'
  filter-regex:
    description: 'Filter out files by regex'
  filter-purl:
    description: 'Filter out purls by regex'
  attach-regex:
    description: 'Attach files content by regex'
  force:
    description: 'Force overwrite cache'
    default: false
  attest-config:
    description: 'Attestation config map'
  attest-name:
    description: 'Attestation config name (default "gensbom")'
  attest-default:
    description: 'Attestation default config, options=[sigstore sigstore-github x509]'
    default: sigstore-github
  scribe-enable:
    description: 'Enable scribe client'
    default: false
  scribe-clientid:
    description: 'Scribe client id' 
  scribe-clientsecret:
    description: 'Scribe access token' 
  scribe-url:
    description: 'Scribe url'
  scribe-loginurl:
    description: 'Scribe auth login url' 
  scribe-audience:
    description: 'Scribe auth audience' 
  context-dir:
    description: 'Context dir' 
  components :
    description: 'Select sbom components groups, options=[metadata layers packages files dep] (default [metadata,layers,packages,files,dep])'

runs:
  using: docker
  image: docker://scribesecuriy.jfrog.io/scribe-docker-public-local/gensbom:latest 
  args:
    - bom
    - ${{ inputs.type }}:${{ inputs.target }}
    - --verbose=${{ inputs.verbose }}
    - ${{ inputs.config && '--config=' }}${{ inputs.config }}
    - ${{ inputs.format && '--format=' }}${{ inputs.format }}
    - ${{ inputs.name && '--name=' }}${{ inputs.name }}
    - ${{ inputs.label && '--label=' }}${{ inputs.label }}
    - ${{ inputs.env && '--env=' }}${{ inputs.env }}
    - ${{ inputs.filter-regex && '--filter-regex=' }}${{ inputs.filter-regex }}
    - ${{ inputs.filter-purl && '--filter-purl=' }}${{ inputs.filter-purl }}
    - ${{ inputs.attach-regex && '--attach-regex=' }}${{ inputs.attach-regex }}
    - --context-type=github
    - ${{ inputs.output-directory && '--output-directory=' }}${{ inputs.output-directory }}
    - ${{ inputs.force && '--force=' }}${{ inputs.force }}
    - ${{ inputs.attest-name && '--attest.name=' }}${{ inputs.attest-name }}
    - ${{ inputs.attest-default && '--attest.default=' }}${{ inputs.attest-default }}
    - ${{ inputs.attest-default && '--attest.default=' }}${{ inputs.attest-default }}
    - ${{ inputs.scribe-enable && '--scribe.enable=' }}${{ inputs.scribe-enable }}
    - ${{ inputs.scribe-clientid && '--scribe.clientid=' }}${{ inputs.scribe-clientid }}
    - ${{ inputs.scribe-clientsecret && '--scribe.clientsecret=' }}${{ inputs.scribe-clientsecret }}
    - ${{ inputs.scribe-url && '--scribe.url=' }}${{ inputs.scribe-url }}
    - ${{ inputs.scribe-loginurl && '--scribe.loginurl=' }}${{ inputs.scribe-loginurl }}
    - ${{ inputs.scribe-audience && '--scribe.auth0.audience=' }}${{ inputs.scribe-audience }}
    - ${{ inputs.context-dir && '--scribe.context-dir=' }}${{ inputs.context-dir }}
    - ${{ inputs.components && '--components=' }}${{ inputs.components }}


branding:
  icon: shield
  color: green
