name: 'Bomber: bom'
description: 'Generates a Software Bill Of Materials (SBOM) from container images and filesystems'
author: Mikey Strauss
outputs:
  output-file:
    description: 'Bom output file path'
inputs:
  type:
    description: 'Target source type options=[docker,docker-archive, oci-archive, dir, registry]'
    default: registry
  target:
    description: 'Target object name format=[<image:tag>, <dir_path>]'
    required: true
  verbose:
    description: 'Increase verbosity (-v = info, -vv = debug)'
    default: 0
  config:
    description: 'Application config file'
  format:
    description: 'Sbom formatter, options=[cyclonedx-json cyclonedx-xml attest-cyclonedx-json statement-cyclonedx-json]'
    default: cyclonedxjson
  format2:
    description: 'Sbom formatter, options=[cyclonedx-json cyclonedx-xml attest-cyclonedx-json statement-cyclonedx-json]'
  format3:
    description: 'Sbom formatter, options=[cyclonedx-json cyclonedx-xml attest-cyclonedx-json statement-cyclonedx-json]'
  output-directory:
    description: 'Report output directory'
    default: ./bomber_reports
  output-file:
    description: 'Output result to file'
  name:
    description: 'Custom/project name'
  label:
    description: 'Custom label'
  label2:
    description: 'Custom label 2'
  label3:
    description: 'Custom label 3'
  env:
    description: 'Custom env'
  env2:
    description: 'Custom env 2'
  env3:
    description: 'Custom env 3'
  filter-regex:
    description: 'Filter out files by regex'
  filter-regex2:
    description: 'Filter out files by regex 2'
    default: .*\.pyc
  filter-regex3:
    description: 'Filter out files by regex 3'
    default: \.git/.*
  collect-regex:
    description: 'Collect files content by regex'
  collect-regex2:
    description: 'Collect files content by regex'
  collect-regex3:
    description: 'Collect files content by regex'
  force:
    description: 'Force overwrite cache'
    default: false
  attest-config:
    description: 'Attestation config map'
  attest-name:
    description: 'Attestation config name (default "bomber")'
  attest-default:
    description: 'Attestation default config, options=[sigstore sigstore-github x509]'
    default: sigstore-github
  scribe-enable:
    description: 'Enable scribe client'
    default: false
  scribe-clientid:
    description: 'Scribe client id' 
  scribe-clientsecret:
    description: 'Scribe access token' 
  scribe-url:
    description: 'Scribe url' 
  context-dir:
    description: 'Context dir' 

runs:
  using: docker
  image: docker://scribesecuriy.jfrog.io/scribe-docker-public-local/bomber:latest 
  args:
    - bom
    - ${{ inputs.type }}:${{ inputs.target }}
    - --verbose=${{ inputs.verbose }}
    - ${{ inputs.config && '--config=' }}${{ inputs.config }}
    - ${{ inputs.format && '--format=' }}${{ inputs.format }}
    - ${{ inputs.format2 && '--format=' }}${{ inputs.format2 }}
    - ${{ inputs.format3 && '--format=' }}${{ inputs.format3 }}
    - ${{ inputs.name && '--name=' }}${{ inputs.name }}
    - ${{ inputs.label && '--label=' }}${{ inputs.label }}
    - ${{ inputs.label2 && '--label=' }}${{ inputs.label2 }}
    - ${{ inputs.label3 && '--label=' }}${{ inputs.label3 }}
    - ${{ inputs.env && '--env=' }}${{ inputs.env }}
    - ${{ inputs.env2 && '--env=' }}${{ inputs.env2 }}
    - ${{ inputs.env3 && '--env=' }}${{ inputs.env3 }}
    - ${{ inputs.filter-regex && '--filter-regex=' }}${{ inputs.filter-regex }}
    - ${{ inputs.filter-regex2 && '--filter-regex=' }}${{ inputs.filter-regex2 }}
    - ${{ inputs.filter-regex3 && '--filter-regex=' }}${{ inputs.filter-regex3 }} 
    - ${{ inputs.collect-regex && '--collect-regex=' }}${{ inputs.collect-regex }}
    - ${{ inputs.collect-regex2 && '--collect-regex=' }}${{ inputs.collect-regex2 }}
    - ${{ inputs.collect-regex3 && '--collect-regex=' }}${{ inputs.collect-regex3 }} 
    - --output-directory=${{ inputs.output-directory }}
    - --force=${{ inputs.force }}
    - --context-type=github
    - ${{ inputs.attest-config && '--attest.config=' }}${{ inputs.attest-config }}
    - ${{ inputs.attest-name && '--attest.name=' }}${{ inputs.attest-name }}
    - ${{ inputs.attest-default && '--attest.default=' }}${{ inputs.attest-default }}
    - --scribe.enable=${{ inputs.scribe-enable }}
    - ${{ inputs.scribe-clientid && '--scribe.clientid=' }}${{ inputs.scribe-clientid }}
    - ${{ inputs.scribe-clientsecret && '--scribe.clientsecret=' }}${{ inputs.scribe-clientsecret }}
    - ${{ inputs.scribe-url && '--scribe.url=' }}${{ inputs.scribe-url }}
    - ${{ inputs.context-dir && '--scribe.context-dir=' }}${{ inputs.context-dir }}


branding:
  icon: shield
  color: green
