name: 'Valint: report'
description: 'Valint tool provides a tool to verify integrity of a supply chain'
author: Mikey Strauss
outputs:
  output-file:
    description: 'Report output file path'
inputs:
  verbose:
    description: 'Increase verbosity (-v = info, -vv = debug)'
    default: 1
  config:
    description: 'Application config file'
  output-directory:
    description: 'Output directory path'
    default: ./scribe/valint
  output-file:
    description: 'Output file path'
  scribe-enable:
    description: 'Enable scribe client'
    default: false
  product-key:
    description: 'Custom/project product key'
  scribe-client-id:
    description: 'Scribe client id' 
  scribe-client-secret:
    description: 'Scribe access token' 
  scribe-url:
    description: 'Scribe url' 
  scribe-login-url:
    description: 'Scribe auth login url' 
  scribe-audience:
    description: 'Scribe auth audience' 
  context-dir:
    description: 'Context dir' 
  section:
    description: 'Select report sections'
  integrity:
    description: 'Select report integrity'
  backoff:
    description: 'Backoff duration'
  timeout:  
    description: 'Timeout duration'

runs:
  using: docker
  image: docker://scribesecuriy.jfrog.io/scribe-docker-public-local/valint:dev-latest 
  args:
    - report
    - --verbose=${{ inputs.verbose }}
    - ${{ inputs.config && '--config=' }}${{ inputs.config }} 
    - --context-type=github
    - ${{ inputs.output-directory && '--output-directory=' }}${{ inputs.output-directory }}
    - ${{ inputs.scribe-enable && '--scribe.enable=' }}${{ inputs.scribe-enable }}
    - ${{ inputs.output-file && '--output-file=' }}${{ inputs.output-file }}
    - ${{ inputs.product-key && '--product-key=' }}${{ inputs.product-key }}
    - ${{ inputs.scribe-client-id && '--scribe.client-id=' }}${{ inputs.scribe-client-id }}
    - ${{ inputs.scribe-client-secret && '--scribe.client-secret=' }}${{ inputs.scribe-client-secret }}
    - ${{ inputs.scribe-url && '--scribe.url=' }}${{ inputs.scribe-url }}
    - ${{ inputs.scribe-login-url && '--scribe.login-url=' }}${{ inputs.scribe-login-url }}
    - ${{ inputs.scribe-audience && '--scribe.auth.audience=' }}${{ inputs.scribe-audience }}
    - ${{ inputs.context-dir && '--context-dir=' }}${{ inputs.context-dir }}
    - ${{ inputs.section && '--section=' }}${{ inputs.section }}
    - ${{ inputs.integrity && '--integrity=' }}${{ inputs.integrity }}
    - ${{ inputs.backoff && '--backoff=' }}${{ inputs.backoff }}
    - ${{ inputs.timeout && '--timeout=' }}${{ inputs.timeout }}

branding:
  icon: shield
  color: blue
