name: 'Valint: report'
description: 'Valint tool provides a tool to verify integrity of a supply chain'
author: Mikey Strauss
outputs:
  output-file:
    description: 'Report output file path'
inputs:
  verbose:
    description: 'Increase verbosity (-v = info, -vv = debug)'
    default: 0
  config:
    description: 'Application config file'
  output-directory:
    description: 'Output directory path'
    default: ./valint_reports
  output-file:
    description: 'Output file path'
  scribe-enable:
    description: 'Enable scribe client'
    default: false
  scribe-clientid:
    description: 'Scribe client id' 
  scribe-clientsecret:
    description: 'Scribe access token' 
  scribe-url:
    description: 'Scribe url' 
  scribe-loginurl:
    description: 'Scribe auth login url' 
  scribe-audience:
    description: 'Scribe auth audience' 
  context-dir:
    description: 'Context dir' 
  section:
    description: 'Select report sections'
  section2:
    description: 'Select report sections2'
  section3:
    description: 'Select report sections3'
  integrity:
    description: 'Select report integrity'
  integrity2:
    description: 'Select report integrity2'
  integrity3:
    description: 'Select report integrity3'


runs:
  using: docker
  image: docker://scribesecuriy.jfrog.io/scribe-docker-public-local/valint:latest 
  args:
    - report
    - --verbose=${{ inputs.verbose }}
    - ${{ inputs.config && '--config=' }}${{ inputs.config }} 
    - --output-directory=${{ inputs.output-directory }}
    - --context-type=github
    - --scribe.enable=${{ inputs.scribe-enable }}
    - ${{ inputs.output-file && '--output-file=' }}${{ inputs.output-file }}
    - ${{ inputs.scribe-clientid && '--scribe.clientid=' }}${{ inputs.scribe-clientid }}
    - ${{ inputs.scribe-clientsecret && '--scribe.clientsecret=' }}${{ inputs.scribe-clientsecret }}
    - ${{ inputs.scribe-url && '--scribe.url=' }}${{ inputs.scribe-url }}
    - ${{ inputs.scribe-loginurl && '--scribe.loginurl=' }}${{ inputs.scribe-loginurl }}
    - ${{ inputs.scribe-audience && '--scribe.auth.audience=' }}${{ inputs.scribe-audience }}
    - ${{ inputs.context-dir && '--scribe.context-dir=' }}${{ inputs.context-dir }}
    - ${{ inputs.section && '--section=' }}${{ inputs.section }}
    - ${{ inputs.section2 && '--section=' }}${{ inputs.section2 }}
    - ${{ inputs.section3 && '--section=' }}${{ inputs.section3 }} 
    - ${{ inputs.integrity && '--integrity=' }}${{ inputs.integrity }}
    - ${{ inputs.integrity2 && '--integrity=' }}${{ inputs.integrity2 }}
    - ${{ inputs.integrity3 && '--integrity=' }}${{ inputs.integrity3 }} 

branding:
  icon: shield
  color: blue
