name: 'Bomber: installer'
description: 'Install bomber - Software Bill Of Materials (SBOM) tool'
author: Mikey Strauss
inputs:
  version:
    description: 'specific version'
    required: false

runs:
  using: "composite"
  steps:
    - name: Installing bomber
      run: |
        #!/bin/bash
        PLATFORM_SCRIPT="$GITHUB_ACTION_PATH/gensbom/installer/scripts/$RUNNER_OS.sh"
        ls -lh $GITHUB_ACTION_PATH/gensbom
        if [ ! -e "$PLATFORM_SCRIPT" ]
        then
          echo "$RUNNER_OS OS not supported by installer"
          exit 1
        fi
        . "$PLATFORM_SCRIPT" ${{ inputs.version }}
      shell: bash
    - name: Installing bomber default config
      run: |
        #!/bin/bash
        set -x
        DEFAULT_CONFIG="$GITHUB_ACTION_PATH/configs/$RUNNER_OS.yaml"
        if [ ! -e "$DEFAULT_CONFIG" ]
        then
          echo "$RUNNER_OS Config not supported by installer"
          exit 1
        fi

        if [ "$(id --user)" -eq "0" ]; then
            sudocmd=""
        else
            sudocmd="sudo"
        fi
        $sudocmd mkdir -p $XDG_CONFIG_HOME/bomber
        $sudocmd cp $DEFAULT_CONFIG $XDG_CONFIG_HOME/bomber/bomber.yaml
      shell: bash
branding:
  icon: shield
  color: green
