name: 'Bomber: bom'
description: 'Generates a Software Bill Of Materials (SBOM) from container images and filesystems'
author: Mikey Strauss
inputs:
  type:
    description: 'Target source type options=[docker,docker-archive, oci-archive, dir, registry]'
    default: registry
  target:
    description: 'Target object name format=[<image:tag>, <dir_path>]'
    required: true
  verbose:
    description: 'Increase verbosity (-v = info, -vv = debug)'
    default: 0
  config:
    description: 'Application config file'
  format:
    description: 'Sbom formatter, options=[cyclonedx-json cyclonedx-xml attest-cyclonedx-json statement-cyclonedx-json]'
    default: cyclonedxjson
  output-directory:
    description: 'Report output directory'
    default: ./bomber_reports
  output-file:
    description: 'Output result to file'
  name:
    description: 'Custom/project name'
  force:
    description: 'Force overwrite cache'
    default: false
  attest-config:
    description: 'Attestation config map'
  attest-name:
    description: 'Attestation config name (default "bomber")'
  attest-default:
    description: 'Attestation default config, options=[sigstore sigstore-github x509]'
    default: sigstore-github
  scribe-enable:
    description: 'Enable scribe client'
    default: false
  scribe-username:
    description: 'Scribe client id' 
  scribe-password:
    description: 'Scribe access token' 
  scribe-url:
    description: 'Scribe url' 

runs:
  using: docker
  image: docker://scribesecuriy.jfrog.io/scribe-docker-public-local/bomber:latest 
  args:
    - bom
    - ${{ inputs.type }}:${{ inputs.target }}
    - --verbose=${{ inputs.verbose }}
    - ${{ inputs.config && '--config=' }}${{ inputs.config }}
    - --format=${{ inputs.format }}
    - ${{ inputs.name && '--name=' }}${{ inputs.name }}
    - --output-directory=${{ inputs.output-directory }}
    - --force=${{ inputs.force }}
    - --context-type=github
    - ${{ inputs.attest-config && '--attest.config=' }}${{ inputs.attest-config }}
    - ${{ inputs.attest-name && '--attest.name=' }}${{ inputs.attest-name }}
    - ${{ inputs.attest-default && '--attest.default=' }}${{ inputs.attest-default }}
    - --scribe.enable=${{ inputs.scribe-enable }}
    - ${{ inputs.scribe-username && '--scribe.username=' }}${{ inputs.scribe-username }}
    - ${{ inputs.scribe-password && '-E --scribe.password=' }}${{ inputs.scribe-password }}
    - ${{ inputs.scribe-url && '--scribe.url=' }}${{ inputs.scribe-url }}

branding:
  icon: shield
  color: green
