name: 'Foot: bom'
description: 'Foot tool provides a tool to verify integrity of a supply chain'
author: Mikey Strauss
outputs:
  output-file:
    description: 'Report output file path'
inputs:
  verbose:
    description: 'Increase verbosity (-v = info, -vv = debug)'
    default: 0
  config:
    description: 'Application config file'
  output-directory:
    description: 'Output directory path'
    default: ./foot_reports
  output-file:
    description: 'Output file path'
  scribe-enable:
    description: 'Enable scribe client'
    default: false
  scribe-clientid:
    description: 'Scribe client id' 
  scribe-clientsecert:
    description: 'Scribe access token' 
  scribe-url:
    description: 'Scribe url' 

runs:
  using: docker
  image: docker://scribesecuriy.jfrog.io/scribe-docker-public-local/bomber:latest 
  args:
    - report
    - --verbose=${{ inputs.verbose }}
    - ${{ inputs.config && '--config=' }}${{ inputs.config }} 
    - --output-directory=${{ inputs.output-directory }}
    - --force=${{ inputs.force }}
    - --context-type=github
    - --scribe.enable=${{ inputs.scribe-enable }}
    - ${{ inputs.scribe-clientid && '--scribe.clientid=' }}${{ inputs.scribe-clientid }}
    - ${{ inputs.scribe-clientsecret && '--scribe.clientsecret=' }}${{ inputs.scribe-clientsecret }}
    - ${{ inputs.scribe-url && '--scribe.url=' }}${{ inputs.scribe-url }}

branding:
  icon: shield
  color: blue
