name: 'tool: installer'
description: 'Scribe tool installer'
author: Mikey Strauss
inputs:
  tools:
    description: 'scribe, tools'
    required: false
    default: 'gensbom,valint'

runs:
  using: "composite"
  steps:
    - name: Installing tool
      run: |
        #!/bin/bash

        function install_APT() {
          TOOLS=$1
          echo "Installing using APT" ${TOOLS}
          PLATFORM_SCRIPT="$GITHUB_ACTION_PATH/scripts/$RUNNER_OS.sh"
          if [ ! -e "$PLATFORM_SCRIPT" ]
          then
            echo "$RUNNER_OS OS not supported by installer"
            exit 1
          fi
          . "$PLATFORM_SCRIPT" ${TOOLS} 
        }

        TOOLS=${{ inputs.tools }}
        if [[ "${TOOLS}" == "fs-tracker" ]]; then
          install_APT ${TOOLS}
        else
          echo "Installing using install script" ${{ inputs.version }} ${{ inputs.tool }} 
          export SCRIBE_TOOLS=${TOOLS//,/ }
          export SCRIBE_DEBUG=${DEBUG}
          export SCRIBE_INSTALL_DIR=/usr/local/bin
          curl -sSfL https://raw.githubusercontent.com/scribe-security/misc/master/install.sh | sh
          if [ $? -eq 0 ] ; then
              echo "Installer success"
          else 
              echo "Installer failed"
              install_APT ${TOOLS}
          fi
        fi
      shell: bash

    - name: Installing tool default config
      run: |
        #!/bin/bash
        set -x
        TOOL_NAME=${{ inputs.tool }}
        DEFAULT_CONFIG="$GITHUB_ACTION_PATH/configs/$TOOL_NAME/$RUNNER_OS.yaml"
        if [ ! -e "$DEFAULT_CONFIG" ]
        then
          echo "$RUNNER_OS Config not supported by installer"
          exit 0
        fi

        if [ "$(id --user)" -eq "0" ]; then
            sudocmd=""
        else
            sudocmd="sudo"
        fi
        $sudocmd mkdir -p $XDG_CONFIG_HOME/$TOOL_NAME
        $sudocmd chmod 755 $XDG_CONFIG_HOME/$TOOL_NAME
        $sudocmd cp $DEFAULT_CONFIG $XDG_CONFIG_HOME/$TOOL_NAME/$TOOL_NAME.yaml
      shell: bash
branding:
  icon: shield
  color: green
